### ISSUE TITLE
Missing `_signal` module on WASI

### ISSUE THREAD

**Issue by d3lm** [RustPython/RustPython#5050] opened 2023-08-28 21:41 UTC
## Summary

If you try to import `platform` you get the following error:

```
>>>>> import platform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "platform", line 119, in <module>
  File "subprocess", line 49, in <module>
  File "signal", line 1, in <module>
ModuleNotFoundError: No module named '_signal'
```

It seems that the `_signal` module is missing. Any idea what this could be or how we could resolve this?

**Comment by fanninpm** [comment] 2023-08-29 00:47
What is your platform? I cannot reproduce on macOS (Ventura, M1) or Linux (Arch Linux, x86_64).

```text
Welcome to the magnificent Rust Python 0.2.0 interpreter 😱 🖖
>>>>> import platform
>>>>> exit()
```

**Comment by d3lm** [comment] 2023-08-29 17:34
Oh sorry, I should have said it's when you compile to WASI.

**Comment by d3lm** [comment] 2023-08-31 07:39
CC @youknowone

**Comment by youknowone** [comment] 2023-08-31 08:59
#4964 is similar issue.
I believe `_signal` is not mendatory for platform. Implementing `_signal` will be the long term correct goal, but patching python library will also make it working.

**Comment by youknowone** [comment] 2023-08-31 15:47
Oh, I was not talking about about user-side, but about updating `Lib/platform.py` from RustPython project to not to refer `_signal`.
Another point. I think WASI anyway will not support `_signal`, right? Then maybe a fake `_signal` module with empty functions like `gc` will be enough.

I also found `platform` is updated in python 3.11 not to require `_signal` when importing. #5060
But still there are encodings problem, so it doesn't work.

**Comment by youknowone** [comment] 2023-08-31 16:03
oh, it was my mistake. platform will be fixed by #5060

**Comment by d3lm** [comment] 2023-08-31 18:48
It depends what that signal module does but WASI has a syscall to send signals to the host process, it's `proc_raise`.

**Comment by d3lm** [comment] 2023-08-31 18:49
But I think as long as it's mostly empty that's fine or at least if we add what we can support.

**Comment by d3lm** [comment] 2023-09-01 06:52
Can confirm that importing `platform` now works 👍 Where would we go to implement things like `platform.release()`?

**Closed** 2024-04-28 01:31 UTC
Labels: C-bug
