### ISSUE TITLE
Simple fibonacci program doesn't finish execution

### ISSUE THREAD

**Issue by Sparkenstein** [RustPython/RustPython#2445] opened 2021-02-10 17:37 UTC
Report type: bug

I wrote a simple fibonacci series program that uses recursion as follows:
```py
import time

def fib(n):
  if n == 1 or n == 0:
    return 1
  return fib(n - 1) + fib(n - 2)
t0 = time.time()
fib(35)
t1 = time.time()
print(f"{(t1 - t0) * 1000} ms")
```

on my machine, this program finishes in `230 ms` on an average with CPython. but with `rustpython` it **did not finish execution**, I waited for 1 minute+ almost. my hardware specs are not that high-end but I believe if CPython can finish execution in 230ms, then rustpython should also finish it within seconds at least if not milliseconds. 

note that it will run anything below value of `30`. for n = 30, it took `16119.468450546265 ms` i.e. `16s` almost. which is a lot high but acceptable assuming rustpython is still in development stage

I am on Ubuntu 20, installed `rustpython` with `cargo install` so I am sure it's a release mode at least. my hardware is i5 4th gen with 8GB ram. let me know if you need anything else

**Comment by pca006132** [comment] 2021-02-14 08:21
On my machine, `fib(33)` run finishes in ~12s with RustPython. Disabling `threading` feature reduces the time to ~9s. Making fast path for integer binops further reduced the time to ~6.3s. Changing `lasti` from `AtomicInt` to `RefCell` further reduces the time to ~5.7s.

From flamegraph, it seems that quite a bit of time is spent on atomic operations, cloning different kinds of stuff, and dropping the objects. I wonder if the atomic operations are really needed, should we add fast paths for primitives, and maybe try and reduce the number of copying.

**Comment by coolreader18** [comment] 2021-02-15 01:37
I think rather than fast paths, we should try adding slots for nb_add, nb_sub, etc. I know CPython has a note in its BINARY_ADD implementation that trying to fast path integer addition generally doesn't yield anything except in microbenchmarks, though maybe that wouldn't apply to us, but we're still using a dictionary lookup for `__add__`

**Comment by coolreader18** [comment] 2021-02-15 01:42
Also, I know that threading has a negative impact on performance, and maybe it shouldn't be enabled as a default feature, but the atomic operations are still necessary to prevent data races/bad caches (or something). However, it's totally possible to use conditional compilation to not use atomic ops when threading is disabled. And maybe it would be possible to use a non-atomic lasti in frame state but have an atomic lasti that we only ever write to, so that f_lasti still is accurate

**Comment by pca006132** [comment] 2021-02-15 03:13
> I think rather than fast paths, we should try adding slots for nb_add, nb_sub, etc. I know CPython has a note in its BINARY_ADD implementation that trying to fast path integer addition generally doesn't yield anything except in microbenchmarks, though maybe that wouldn't apply to us, but we're still using a dictionary lookup for `__add__`

Yup, the overhead should be mostly on the dictionary lookup, this may be fast enough already. Another problem is probably about how integers are stored, the current implementation requires accessing the context for integers, causing a lot of allocation/deallocation, I wonder if it is possible to use a union for `PyObjectRef` to optimize for small integers like `i32`.

> Also, I know that threading has a negative impact on performance, and maybe it shouldn't be enabled as a default feature, but the atomic operations are still necessary to prevent data races/bad caches (or something). However, it's totally possible to use conditional compilation to not use atomic ops when threading is disabled. And maybe it would be possible to use a non-atomic lasti in frame state but have an atomic lasti that we only ever write to, so that f_lasti still is accurate

The problem is, with the current implementation, I don't think threading really benefit computation-intensive applications. Consider the following program:

```python
import threading
import time

a = 0
lock = threading.Lock()

def thread_function():
    global a
    s = 0
    for i in range(1000000):
        s += 1
    with lock:
        a += s

def measure_time(thread_num):
    threads = []
    global a
    a = 0
    for i in range(thread_num):
        threads.append(threading.Thread(target=thread_function))
    t0 = time.time()
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    t1 = time.time()
    return t1 - t0

thread_time = []
for i in range(8):
    thread_time.append(measure_time(i + 1))
print(thread_time)
```
The result is this:
```
[0.8918921947479248, 1.3905704021453857, 1.7531208992004395, 2.1571602821350098, 2.659090042114258, 2.973165512084961, 3.271080732345581, 3.656414270401001]
```
Nearly a straight line. This is probably due to lock contention when everything tries to get the `ctx` lock... but I did not really look into it. The point I want to bring up is, removing GIL but introducing locks for context and a lot of atomic would not really enable us to utilize parallelism for computation-intensive programs, the `ctx` lock is just another GIL.

**Comment by coolreader18** [comment] 2021-02-15 06:33
> the current implementation requires accessing the context for integers, causing a lot of allocation/deallocation

What do you mean by this? Like the integer cache in PyContext? I think that'd reduce unnecessary allocation, since small integers can just reuse existing allocated int objects.

**Comment by pca006132** [comment] 2021-02-15 06:39
> What do you mean by this? Like the integer cache in PyContext? I think that'd reduce unnecessary allocation, since small integers can just reuse existing allocated int objects.

Sorry, I just found that I misunderstood the code, it seems that PyContext would not add more allocation.

Anyway, the allocation and deallocation overhead is pretty large, even for the simple microbenchmark code I wrote in #2460, but idk how to fix that.

**Comment by DimitrisJim** [comment] 2021-10-08 07:55
This currently completes just fine for me (Albeit, slowly! :smile:). I'll be closing for now, feel free to open if it won't finish for you.

**Closed by DimitrisJim** 2021-10-08 07:55 UTC
