### ISSUE TITLE
Ordered Dict fails on pop elemet

### ISSUE THREAD

**Issue by Masorubka1** [RustPython/RustPython#4845] opened 2023-04-04 10:26 UTC
## Feature
<img width="453" alt="image" src="https://user-images.githubusercontent.com/43664538/229763692-943b52ce-d2a7-4188-850e-48f448222679.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/43664538/229763780-f1fad4d0-708b-4118-8ee0-2c6f044f00ab.png">
<img width="522" alt="image" src="https://user-images.githubusercontent.com/43664538/229763820-6d7dffc8-f97e-4a13-b3ba-dd3dab04856c.png">
<img width="684" alt="image" src="https://user-images.githubusercontent.com/43664538/229763867-20f237cf-8b59-4af4-a8f5-1e1d9557d83e.png">

**Comment by JazzGlobal** [comment] 2023-04-09 06:25
What does the tag "C-bug" mean? This also occurs in CPython?

**Comment by DimitrisJim** [comment] 2023-04-09 13:52
Think of it as Category; that's what I've basically done :smile: No, doesn't affect CPython in this case since it fails on one of their tests.

**Comment by JazzGlobal** [comment] 2023-04-09 15:31
Gotcha, thank you!

**Comment by Phosphorescentt** [comment] 2023-04-15 12:48
Possibly fixed here? https://github.com/RustPython/RustPython/pull/4876

**Comment by fanninpm** [comment] 2023-04-15 16:16
@Phosphorescentt It's likely that you treated the symptom instead of the root cause.

**Comment by Phosphorescentt** [comment] 2023-04-15 16:45
Hey @fanninpm - I see that now. Currently resolving in the PR thread. Thanks for the heads up though :)

**Comment by crazymerlyn** [comment] 2024-09-23 23:36
Is this still an issue? Seems like it was fixed in the pr linked above

**Comment by youknowone** [comment] 2024-09-24 05:21
@Phosphorescentt @crazymerlyn Thank you for confirming!

**Closed by youknowone** 2024-09-24 05:21 UTC
Labels: C-bug, A-stdlib
