### ISSUE TITLE
Running `help(help)` and `help(list)` returns errors in REPL

### ISSUE THREAD

**Issue by ArniDagur** [RustPython/RustPython#2056] opened 2020-08-01 20:38 UTC
See the following REPL session:
```
[arni][~/src/RustPython][master][C:(base)]% cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rustpython`
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> help(help)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sdb/src/RustPython/Lib/_sitebuiltins.py", line 104, in __call__
    return pydoc.help(*args, **kwds)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1857, in __call__
    self.help(request)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1916, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1647, in doc
    print(value)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1643, in doc
    pager(render_doc(thing, title, forceload))
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1636, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 386, in document
    pass
  File "/sdb/src/RustPython/Lib/pydoc.py", line 383, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1305, in docclass
    lambda t: t[1] == 'method')
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1251, in spill
    name, mod, object))
  File "/sdb/src/RustPython/Lib/pydoc.py", line 386, in document
    pass
  File "/sdb/src/RustPython/Lib/pydoc.py", line 384, in document
    if inspect.isroutine(object): return self.docroutine(*args)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1357, in docroutine
    signature = None
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1355, in docroutine
    signature = inspect.signature(object)
  File "/sdb/src/RustPython/Lib/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/sdb/src/RustPython/Lib/inspect.py", line 2843, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/sdb/src/RustPython/Lib/inspect.py", line 2293, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/sdb/src/RustPython/Lib/inspect.py", line 2173, in _signature_from_function
    name = arg_names[pos_count + keyword_only_count]
IndexError: Index out of bounds!
>>>>> help(list)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sdb/src/RustPython/Lib/_sitebuiltins.py", line 104, in __call__
    return pydoc.help(*args, **kwds)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1857, in __call__
    self.help(request)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1916, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1647, in doc
    print(value)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1643, in doc
    pager(render_doc(thing, title, forceload))
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1636, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 386, in document
    pass
  File "/sdb/src/RustPython/Lib/pydoc.py", line 383, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1305, in docclass
    lambda t: t[1] == 'method')
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1251, in spill
    name, mod, object))
  File "/sdb/src/RustPython/Lib/pydoc.py", line 386, in document
    pass
  File "/sdb/src/RustPython/Lib/pydoc.py", line 384, in document
    if inspect.isroutine(object): return self.docroutine(*args)
  File "/sdb/src/RustPython/Lib/pydoc.py", line 1350, in docroutine
    title = self.bold(name) + ' = ' + realname
TypeError: Cannot add __add__ =  and 'NoneType' object
```
* Version: latest `master`
* OS: Gentoo Linux
* System: `Linux arni-pc 5.7.9-gentoo-x86_64 #1 SMP Wed Jul 22 03:28:52 GMT 2020 x86_64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz GenuineIntel GNU/Linux`

**Comment by coolreader18** [comment] 2020-08-01 22:47
Thanks for the report! There are a lot of issues like this with pydoc, often related to very subtle differences with how we "do" objects vs CPython

**Comment by frazar** [comment] 2020-10-28 11:02
I tried to reproduce the errors with the latest `master`, but everything seems to be working correctly.

```
$ cargo -V
cargo 1.47.0 (f3c7e066a 2020-08-28)
$ git rev-parse HEAD
3c9ad2378bd18bb2febfd29eb6e4ff14a4c21c9d
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/rustpython`
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> help(help)
Help on _Helper in module _sitebuiltins object:

class _Helper(builtins.object)
 |  Define the builtin 'help'.
 |  
 |  This is a wrapper around pydoc.help that provides a helpful message
 |  when 'help' is typed at the Python interactive prompt.
 |  
 |  Calling help() at the Python prompt starts an interactive help session.
 |  Calling help(thing) prints help for the python object 'thing'.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args, **kwds)
 |  
 |  __delattr__(...)
 |  
 |  __dir__(...)
 |  
 |  __eq__(...)
 |  
 |  __format__(...)
 |  
 |  __ge__(...)
 |  
 |  __getattribute__(...)
 |  
 |  __gt__(...)
 |  
 |  __hash__(...)
 |  
 |  __init__(...)
 |  
 |  __le__(...)
 |  
 |  __lt__(...)
 |  
 |  __ne__(...)
 |  
 |  __reduce__(...)
 |  
 |  __reduce_ex__(...)
 |  
 |  __repr__(self)
 |  
 |  __setattr__(...)
 |  
 |  __str__(...)
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __init_subclass__ = <bound method of <class '_sitebuiltins._Helper'>>
 |  __subclasshook__ = <bound method of <class '_sitebuiltins._Helper'>>
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__ = <bound method of <class '_sitebuiltins._Helper'>>
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      The most base type
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __class__ = <class 'type'>
 |      type(object_or_name, bases, dict)
 |      type(object) -> the object's type
 |      type(name, bases, dict) -> a new type

>>>>> help(list)
Help on class list in module __main__:

class list(object)
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |  
 |  __bool__(...)
 |  
 |  __contains__(...)
 |  
 |  __delattr__(...)
 |  
 |  __delitem__(...)
 |  
 |  __dir__(...)
 |  
 |  __eq__(...)
 |  
 |  __format__(...)
 |  
 |  __ge__(...)
 |  
 |  __getattribute__(...)
 |  
 |  __getitem__(...)
 |  
 |  __gt__(...)
 |  
 |  __hash__(...)
 |  
 |  __iadd__(...)
 |  
 |  __imul__(...)
 |  
 |  __init__(...)
 |  
 |  __iter__(...)
 |  
 |  __le__(...)
 |  
 |  __len__(...)
 |  
 |  __lt__(...)
 |  
 |  __mul__(...)
 |  
 |  __ne__(...)
 |  
 |  __reduce__(...)
 |  
 |  __reduce_ex__(...)
 |  
 |  __repr__(...)
 |  
 |  __reversed__(...)
 |  
 |  __rmul__(...)
 |  
 |  __setattr__(...)
 |  
 |  __setitem__(...)
 |  
 |  __sizeof__(...)
 |  
 |  __str__(...)
 |  
 |  append(...)
 |  
 |  clear(...)
 |  
 |  copy(...)
 |  
 |  count(...)
 |  
 |  extend(...)
 |  
 |  index(...)
 |  
 |  insert(...)
 |  
 |  pop(...)
 |  
 |  remove(...)
 |  
 |  reverse(...)
 |  
 |  sort(...)
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __init_subclass__ = <bound method of <class 'list'>>
 |  __subclasshook__ = <bound method of <class 'list'>>
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__ = <bound method of <class 'list'>>
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __class__ = <class 'type'>
 |      type(object_or_name, bases, dict)
 |      type(object) -> the object's type
 |      type(name, bases, dict) -> a new type

>>>>> 
```

**Comment by coolreader18** [comment] 2020-10-28 16:13
Oh, yep, I think a month or 2 ago we gave all builtin methods names, so this should be fixed now.

**Closed by coolreader18** 2020-10-28 16:13 UTC
