### ISSUE TITLE
Long parameter lists cause core dumped

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4858] opened 2023-04-06 11:17 UTC
If a  function takes long parameter lists, the rustpython  reports a core dumped

test.py
```
def f(*args): return len(args)
f(*([0]*(2**32+1)))
```
Crash message:
```
memory allocation of 34359738376 bytes failed
Aborted (core dumped)

```

Environment:
Ubuntu 18.04
rustpython v0.2.0

**Comment by DimitrisJim** [comment] 2023-04-06 18:06
Thanks, this is basically a duplicate of #3494. With fallible allocations, we should be able to make this raise a `MemoryError` in the same way CPython does. 

(Note that this isn't an issue with the fact that it is an arg but just the fact that we try to allocate something so large).

Thanks again for opening these issues, even if some are duplicate.

**Closed by DimitrisJim** 2023-04-06 18:06 UTC
