### ISSUE TITLE
Fix exception string representation

### ISSUE THREAD

**Issue by vokar** [RustPython/RustPython#322] opened 2019-02-05 06:39 UTC
Writing a python test for a PR, I noticed that the RustPython's string representation of exceptions is different from the one we have in cpython.

For instance, the following code
```python
try:
    "hi"[-4]
except IndexError as error:
    print(error)
```
will print "IndexError: string index out of range" in RustPython and "string index out of range" in cpython. As you can see, the difference is the type name in the beginning.

So if there is no reason for such existing implementation, I can send a PR editing [this two lines of code](https://github.com/RustPython/RustPython/blob/master/vm/src/exceptions.rs#L78-L79).
@windelbouwman, what do you think?

**Comment by windelbouwman** [comment] 2019-02-05 22:40
I am unaware of any specific reason. I like the clarity by giving the type of the exception. I would leave this as is for now.

**Comment by cthulahoops** [comment] 2019-02-06 10:04
I think we should aim for consistency with Cpython here. You can get the name of the exception if you need it, but it looks like str just gives the message.

**Comment by windelbouwman** [comment] 2019-07-06 09:11
@vokar I believe this issue is now resolved. Could you check it, and close the issue if this is now operating as per the expected behavior?

**Comment by vokar** [comment] 2019-07-06 12:36
> @vokar I believe this issue is now resolved. Could you check it, and close the issue if this is now operating as per the expected behavior?

Yeah, almost. Now we have `string index out of range` in CPython 3.7.3 but `'string index out of range'` in RustPython with the apostrophes, so the following code will print `True` and `False` using them respectively:
```python
try:
    "hi"[-4]
except IndexError as error:
    print(str(error) == "string index out of range")
```

**Comment by dralley** [comment] 2019-09-24 23:39
Looks like it's fixed for strings, specifically, but the messages are still different in general

CPython:
```
>>> try:
...     "hi"[-4]
... except IndexError as error:
...     print(error)
... 
string index out of range
>>> l = [0, 1, 2]
>>> try:
...     l[-4]
... except IndexError as error:
...     print(error)
... 
list index out of range
```

RustPython

```
>>>>> try:
.....    "hi"[-4]
.....except IndexError as error:
.....    print(error)
'string index out of range'
>>>>> l = [0, 1, 2]
>>>>> try:
.....     l[-4]
..... except IndexError as error:
.....     print(error)
..... 
'Index out of bounds!'
>>>>> 
```

**Comment by dralley** [comment] 2019-09-24 23:40
Maybe change the name of this issue to match?

**Comment by youknowone** [comment] 2020-01-02 12:29
I've checked we are aiming not to exactly replicating error messages with CPython. (probably from gitter)

Please reopen this issue if I misunderstand the issue or the error message policy of rustpython.

**Closed by youknowone** 2020-01-02 12:29 UTC
