### ISSUE TITLE
Bad cross-type comparison between float and int

### ISSUE THREAD

**Issue by lifthrasiir** [RustPython/RustPython#1069] opened 2019-06-29 04:47 UTC
```python
>>>>> a = 1.0; b = 1
>>>>> while True: a *= 2; b *= 2; assert a > b - 1, b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: 18014398509481984
>>>>> 2**54
18014398509481984
>>>>> 2.**54 > 2**54 - 1
False
```

The loop should not fail, probably except for the eventual MemoryError or so. We currently compare them by converting int to float, and thus by losing precision. Note that the other way also doesn't work because we then lose fractional bits. The corresponding [CPython code](https://github.com/python/cpython/blob/80097e089ba22a42d804e65fbbcf35e5e49eed00/Objects/floatobject.c#L341-L535) is understandably complex.

**Comment by silmeth** [comment] 2019-06-29 11:16
This is similar to #373 (int and float equality checks converted ints to floats), which I fixed by doing two comparisons `int1 == int2 && float1 == float2`.

Perhaps a similar logic could be used in less-than and bigger-than comparisons?

**Comment by silmeth** [comment] 2019-06-29 13:37
I think treating cross-type `a > b` as if desugared to `int(a) > int(b) or float(a) > float(b)` would be a good start (and similarly for the inverse).

```python3
Welcome to the magnificent Rust Python 0.0.1 interpreter 😱 🖖
>>>>> i = 2**54; f = 2.**54
>>>>> int(f) > int(i-1) or float(f) > float(i-1)
True
>>>>> int(f) > int(i) or float(f) > float(i)
False
>>>>> f = 0.3; i = 1
>>>>> int(i) > int(f) or float(i) > float(f)
True
```

Then we’d just need to take into account
* `int`s too big to convert to f64 (always bigger than any non-`inf`, non-`nan` float if positive; smaller if negative),
* `inf`s (bigger/smaller than any `int` depending on sign),
* `nan`s (`False` for any comparison).

I’ll try to fix it this way.

**Comment by lifthrasiir** [comment] 2019-06-29 14:58
> I think treating cross-type `a > b` as if desugared to `int(a) > int(b) or float(a) > float(b)` would be a good start (and similarly for the inverse).

I'm afraid that this won't work.

```python
>>> i = 2**53; f = 2.**53
>>> int(f) > int(i-.5) or float(f) > float(i-.5)
False
```

I was planning a robust fix that doesn't involve conversions (though it can allocate more than required, this is a fundamental problem with num-bigint :-S). Please allow me some hours :-)

**Comment by silmeth** [comment] 2019-06-29 15:01
> I'm afraid that this won't work.
> 
> ```python
> >>> i = 2**53; f = 2.**53
> >>> int(f) > int(i-.5) or float(f) > float(i-.5)
> False
> ```

What’s wrong with that? In CPython:

```python3
>>> i = 2**53; f = 2.**53
>>> f > (i-.5)
False
```

So I’d say it is expected behaviour.

**Comment by lifthrasiir** [comment] 2019-06-29 15:09
Oops, I missed the swapped variable order, and should have said 52 instead of 53... Yeah, my bad. I'm still unsure because the int-to-float conversion rounds to nearest and that can possibly affect the comparison however.

**Comment by silmeth** [comment] 2019-06-29 15:11
In case of `2.**52 > (2**52 - .5)` it is still a float-float comparison and will work as intended (won’t even enter the float-int code path).

But of course if you have a better solution, I absolutely don’t mind you implementing it. :)

**Closed** 2019-06-30 07:25 UTC
Labels: feat
