### ISSUE TITLE
Implement Locals Builtin

### ISSUE THREAD

**Issue by rmliddle** [RustPython/RustPython#147] opened 2018-10-01 03:55 UTC
Running the locals builtin function causes a type exception
```python
>>>>> locals()
thread 'main' panicked at 'Object doesn't have a type!', vm/src/pyobject.rs:379:21
```

**Comment by Tom1380** [comment] 2019-02-09 13:34
The issue is no longer present.

**Comment by rmliddle** [comment] 2019-02-10 04:12
It no longer throws an exception, however its behaviour is still somewhat different to that of `python3`.

Expected:
```python
python
>>> locals()
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}
```

Actual:
```python
>>>>> locals()
>>>>> 
```

**Comment by windelbouwman** [comment] 2019-06-16 18:45
@rmliddle this issue seems to be fixed now. Should the issue be closed?

**Closed** 2019-06-17 09:29 UTC
Labels: help wanted
